### ISSUE TITLE
documentation of regridder algorithms

### ISSUE THREAD

**Issue by susburrows** [doutriaux1/regrid#2]
We would like to have some documentation of the regridding methods and procedure for both the climatology and diagnostics scripts (which algorithms were used, how were weights calculated, including the name of tool, and methods used to calculate the weights (e.g. SCRIP low/high order), and once weight is calculated what tool was used to do the regridding).

I also created an issue for this in the uvcmetrics repository.

**Comment by doutriaux1** [comment]
@susburrows I see it at: https://github.com/UV-CDAT/uvcmetrics/issues/66
closing it here since it really doesn't involves the regrid at all
